services:
  - type: web
    name: ept-task-manager
    env: docker
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: GOOGLE_SHEET_USERID
        value: 18d4_bErbafBMoxqnxpK9F6GZ49JUgU8O0lqMBdE7ZX8
      - key: GOOGLE_SHEET_USERRANGE
        value: Users.Resustainability!A:I
      - key: GOOGLE_SHEET_TASKSID
        value: 1sMjUrZBEJqHbEdjZWe25_cQGnW86S-qSOwV92wEqPXw
      - key: GOOGLE_SHEET_TASKSRANGE
        value: Tasks.Resustainability!A:M
      - key: GOOGLE_SHEET_EMPID
        value: 1gSMiglIfJD6VyBEp9VU0wntP2MJ0L9unxvRGdMi8-38
      - key: GOOGLE_SHEET_EMPRANGE
        value: Employees.Resustainability!A:C
      - key: GOOGLE_SHEET_CREDENTIALS_FIRST
        value: src/main/resources/my-project-ept-new-42ae1c1963d4.json
      - key: GOOGLE_SHEET_CREDENTIALS_SECOND
        value: src/main/resources/my-project-ept-new-6f7794c25cfb.json
      - key: GOOGLE_SHEET_CREDENTIALS_THIRD
        value: src/main/resources/my-project-ept-new-5d96b7c31f3d.json
      - key: EMAIL_USERNAME
        value: task.list@resustainability.com
      - key: EMAIL_PASSWORD
        value: pelmppumxyqahqky
